title:              Nikeardita Blog
email:              ardytaeunike@gmail.com
description:        A Blog by Eunike
author:             Nikeardita
baseurl:            "/"
url:                "https://dita.my.id"
permalink: /:categories/:title:output_ext


# Social Profiles
github_username:    nikeardita
facebook_username:  eunikeardita
instagram_username: eunike_ardita
youtube_link: https://www.youtube.com/channel/UC_rK686n1S0IGjC0FZSoMzQ
youtube_channel: UC_rK686n1S0IGjC0FZSoMzQ
linkedin_username: 
twitter_username: 

# Disqus
discus-identifier: nikeardita # add your discus identifier

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/category/' }
    - { Tags: '/blog/tag/' }
  About:          
    - '/about/'
  Contact: 
    - '/contact/'

# Where are tags and categories displayed
tag_page: '/blog/tag/'
category_page: '/blog/category/'

# Build settings
markdown:           kramdown
paginate:         5
paginate_path:    '/blog/page:num'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
